import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, ChevronLeft, ChevronRight, Facebook, Instagram, Menu, MessageCircle, Phone, Play, Quote, Sparkles, Star, X } from 'lucide-react'
import './styles.css'

const slides = [
  { image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=2000&q=90', eyebrow: 'Bunso Catering', title: 'Made for the\nmoments that matter.', text: 'Exceptional menus, artful service and a table your guests will remember.' },
  { image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=2000&q=90', eyebrow: 'The Art of Gathering', title: 'Beautifully\nconsidered celebrations.', text: 'From intimate dinners to once-in-a-lifetime weddings.' },
  { image: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=2000&q=90', eyebrow: 'A Taste of Bunso', title: 'A feast for\nevery sense.', text: 'Seasonal flavours, served with warmth and effortless style.' },
]

const packages = [
  { no: '01', title: 'Weddings', text: 'A menu as personal as your love story, served with quiet confidence and a touch of theatre.', image: 'https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1000&q=80' },
  { no: '02', title: 'Private Dining', text: 'Generous, intimate and entirely yours. Exceptional food for the people closest to you.', image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1000&q=80' },
  { no: '03', title: 'Corporate', text: 'Thoughtful hospitality that makes every client, colleague and milestone feel valued.', image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1000&q=80' },
]

const gallery = [
  'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1478146896981-b80fe463b330?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1200&q=85',
]

function Logo() { return <a href="#home" className="font-display text-3xl font-semibold tracking-tight text-white">bunso<span className="text-gold">.</span></a> }
function SectionLabel({ children, dark = false }) { return <p className={`mb-5 text-[10px] font-bold uppercase tracking-luxe ${dark ? 'text-gold' : 'text-gold'}`}>{children}</p> }

function App() {
  const [slide, setSlide] = useState(0); const [menu, setMenu] = useState(false); const [lightbox, setLightbox] = useState(null); const [sent, setSent] = useState(false)
  useEffect(() => { const id = setInterval(() => setSlide(s => (s + 1) % slides.length), 6500); return () => clearInterval(id) }, [])
  useEffect(() => { const onKey = e => { if (e.key === 'Escape') setLightbox(null) }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [])
  const next = () => setSlide(s => (s + 1) % slides.length), prev = () => setSlide(s => (s - 1 + slides.length) % slides.length)
  const nav = ['About', 'Packages', 'Gallery', 'Testimonials', 'Contact']
  return <main className="overflow-hidden bg-cream text-ink">
    <header className="absolute z-20 w-full px-6 py-6 md:px-12"><div className="mx-auto flex max-w-7xl items-center justify-between"><Logo /><nav className="hidden items-center gap-8 md:flex">{nav.map(n => <a key={n} href={`#${n.toLowerCase()}`} className="nav-link">{n}</a>)}<a href="#booking" className="gold-button px-5 py-3 text-[10px]">Enquire Now</a></nav><button aria-label="Open menu" className="text-white md:hidden" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div>{menu && <nav className="mt-4 flex flex-col gap-4 border border-white/20 bg-ink p-6 md:hidden">{nav.map(n => <a onClick={() => setMenu(false)} key={n} href={`#${n.toLowerCase()}`} className="nav-link">{n}</a>)}<a href="#booking" onClick={() => setMenu(false)} className="text-gold">Enquire Now</a></nav>}</header>

    <section id="home" className="relative min-h-[720px] h-screen max-h-[900px] bg-ink text-white"><div className="absolute inset-0">{slides.map((s, i) => <img key={s.image} src={s.image} alt="Elegant Bunso Catering event" className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-[1600ms] ${i === slide ? 'opacity-70' : 'opacity-0'}`} />)}<div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/30 to-black/10" /></div><div className="relative mx-auto flex h-full max-w-7xl items-center px-6 pt-20 md:px-12"><div className="max-w-2xl"><p className="mb-6 text-[10px] font-bold uppercase tracking-luxe text-gold">{slides[slide].eyebrow}</p><h1 className="whitespace-pre-line font-display text-6xl font-medium leading-[.87] sm:text-7xl md:text-8xl">{slides[slide].title}</h1><p className="mt-7 max-w-md text-sm leading-7 text-white/80">{slides[slide].text}</p><a href="#booking" className="mt-9 inline-flex items-center gap-3 border-b border-gold pb-2 text-[11px] font-bold uppercase tracking-luxe text-white">Plan your event <ArrowRight size={15} className="text-gold" /></a></div></div><div className="absolute bottom-10 left-6 flex items-center gap-4 md:left-12"><button aria-label="Previous slide" onClick={prev} className="hero-control"><ChevronLeft size={18} /></button><span className="text-xs">0{slide + 1} <span className="text-white/50">/ 0{slides.length}</span></span><button aria-label="Next slide" onClick={next} className="hero-control"><ChevronRight size={18} /></button></div><a href="#about" className="absolute bottom-10 right-6 hidden rotate-90 text-[10px] uppercase tracking-luxe text-white/70 md:block">Scroll to discover</a></section>

    <section id="about" className="mx-auto grid max-w-7xl gap-14 px-6 py-24 md:grid-cols-2 md:items-center md:px-12 md:py-36"><div className="relative"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85" alt="Beautifully plated catering dish" className="h-[500px] w-full object-cover" /><div className="absolute -bottom-6 -right-3 hidden h-40 w-44 border border-gold bg-cream p-5 md:block"><p className="font-display text-5xl text-gold">15</p><p className="mt-1 text-[10px] font-bold uppercase tracking-luxe">Years of<br />gathering</p></div></div><div className="md:pl-14"><SectionLabel>Our story</SectionLabel><h2 className="font-display text-5xl leading-none sm:text-6xl">Every gathering<br /><em className="font-normal text-gold">deserves a little magic.</em></h2><p className="mt-8 max-w-lg text-sm leading-8 text-stone">At Bunso, we believe food is the heart of every memorable occasion. We bring together expressive flavours, generous hospitality and a sharp eye for the beautiful details.</p><p className="mt-4 max-w-lg text-sm leading-8 text-stone">What began around a family table has grown into a passionate team trusted with life's biggest celebrations.</p><a href="#packages" className="outline-button mt-9">Discover our story <ArrowRight size={15} /></a></div></section>

    <section id="packages" className="bg-ink px-6 py-24 text-white md:px-12 md:py-32"><div className="mx-auto max-w-7xl"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><SectionLabel>What we do</SectionLabel><h2 className="font-display text-5xl leading-none sm:text-6xl">Made to feel <em className="font-normal text-gold">entirely yours.</em></h2></div><p className="max-w-sm text-sm leading-7 text-white/60">Select a starting point, then let us create a celebration with your signature all over it.</p></div><div className="grid gap-px bg-white/15 md:grid-cols-3">{packages.map(p => <article key={p.title} className="group bg-ink p-6 md:p-7"><div className="overflow-hidden"><img src={p.image} alt={p.title} className="h-56 w-full object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" /></div><p className="mt-7 text-xs text-gold">{p.no}</p><h3 className="mt-3 font-display text-4xl">{p.title}</h3><p className="mt-4 min-h-20 text-sm leading-7 text-white/55">{p.text}</p><a href="#booking" className="mt-5 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-luxe text-gold">Explore <ArrowRight size={14} /></a></article>)}</div></div></section>

    <section id="gallery" className="px-6 py-24 md:px-12 md:py-32"><div className="mx-auto max-w-7xl"><div className="mb-12 text-center"><SectionLabel>From our table</SectionLabel><h2 className="font-display text-5xl leading-none sm:text-6xl">A little <em className="font-normal text-gold">inspiration.</em></h2></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.map((image, i) => <button aria-label={`Open gallery image ${i + 1}`} onClick={() => setLightbox(i)} key={image} className={`gallery-item ${i === 0 || i === 3 ? 'md:row-span-2' : ''}`}><img src={image} alt={`Bunso event gallery ${i + 1}`} className="h-full w-full object-cover" /><span className="gallery-overlay"><Sparkles size={20} /></span></button>)}</div></div></section>

    <section id="testimonials" className="relative bg-[#e8dfcf] px-6 py-24 text-center md:px-12 md:py-32"><Quote className="mx-auto mb-5 text-gold" size={34} fill="currentColor" /><div className="mx-auto max-w-4xl"><p className="font-display text-3xl leading-tight sm:text-5xl">“Bunso made our wedding feel like the most generous, joyous dinner party imaginable. The food was astonishing and every detail was simply beautiful.”</p><div className="mt-8 flex justify-center gap-1 text-gold">{[1,2,3,4,5].map(n => <Star key={n} size={14} fill="currentColor" />)}</div><p className="mt-4 text-[10px] font-bold uppercase tracking-luxe">Clara &amp; Sam — Kangaroo Valley</p></div></section>

    <section id="booking" className="bg-ink px-6 py-24 text-white md:px-12 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 md:grid-cols-[.8fr_1.2fr]"><div><SectionLabel>Start a conversation</SectionLabel><h2 className="font-display text-5xl leading-none sm:text-6xl">Let's make it<br /><em className="font-normal text-gold">unforgettable.</em></h2><p className="mt-7 max-w-sm text-sm leading-7 text-white/60">Tell us a little about your celebration. We'll be in touch within two business days with the next delicious steps.</p><div className="mt-10 space-y-4 text-sm text-white/70"><a className="flex items-center gap-3 hover:text-gold" href="tel:+61290000000"><Phone size={16} className="text-gold" /> +61 2 9000 0000</a><a className="flex items-center gap-3 hover:text-gold" href="mailto:hello@bunsocatering.com"><MessageCircle size={16} className="text-gold" /> hello@bunsocatering.com</a></div></div><form onSubmit={e => { e.preventDefault(); setSent(true) }} className="grid gap-x-6 gap-y-7 sm:grid-cols-2">{[['Name', 'text'], ['Email', 'email'], ['Phone', 'tel'], ['Event date', 'date']].map(([label, type]) => <label key={label} className="form-label">{label}<input required type={type} className="form-input" /></label>)}<label className="form-label">Event type<select required defaultValue="" className="form-input"><option value="" disabled>Select an occasion</option><option>Wedding</option><option>Private dining</option><option>Corporate event</option><option>Other celebration</option></select></label><label className="form-label">Guest count<input required type="number" min="1" placeholder="e.g. 80" className="form-input" /></label><label className="form-label sm:col-span-2">Tell us more<textarea className="form-input resize-none" rows="3" placeholder="Your vision, venue or anything else we should know..." /></label><div className="sm:col-span-2"><button className="gold-button w-full py-4" type="submit">{sent ? 'Thank you — we’ll be in touch!' : 'Send your enquiry'} <ArrowRight size={15} /></button></div></form></div></section>

    <footer id="contact" className="bg-[#060605] px-6 py-12 text-white md:px-12"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-4"><div><Logo /><p className="mt-4 text-xs leading-6 text-white/50">Food, feeling and the art of a good time.</p></div><div><p className="footer-title">Visit</p><p className="footer-text">18 Harvest Lane<br />Surry Hills, NSW 2010</p></div><div><p className="footer-title">Connect</p><a href="mailto:hello@bunsocatering.com" className="footer-text block hover:text-gold">hello@bunsocatering.com</a><a href="tel:+61290000000" className="footer-text block hover:text-gold">+61 2 9000 0000</a></div><div><p className="footer-title">Follow along</p><div className="flex gap-4 text-gold"><a aria-label="Instagram" href="#"><Instagram size={18} /></a><a aria-label="Facebook" href="#"><Facebook size={18} /></a></div></div></div><div className="mx-auto mt-12 flex max-w-7xl flex-col justify-between gap-2 border-t border-white/10 pt-5 text-[10px] uppercase tracking-wider text-white/35 sm:flex-row"><span>© {new Date().getFullYear()} Bunso Catering</span><span>Made for meaningful moments</span></div></footer>
    <a aria-label="Chat with Bunso Catering on Messenger" className="messenger" href="https://m.me/" target="_blank" rel="noreferrer"><MessageCircle size={24} fill="white" /></a>
    {lightbox !== null && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 p-5" role="dialog" aria-modal="true"><button aria-label="Close gallery" className="absolute right-6 top-6 text-white" onClick={() => setLightbox(null)}><X size={28} /></button><button aria-label="Previous image" onClick={() => setLightbox((lightbox - 1 + gallery.length) % gallery.length)} className="absolute left-4 text-white md:left-10"><ChevronLeft size={32} /></button><img src={gallery[lightbox]} alt="Expanded Bunso event gallery" className="max-h-[88vh] max-w-[88vw] object-contain" /><button aria-label="Next image" onClick={() => setLightbox((lightbox + 1) % gallery.length)} className="absolute right-4 text-white md:right-10"><ChevronRight size={32} /></button></div>}
  </main>
}
createRoot(document.getElementById('root')).render(<App />)
